[package]
name = "cwillsey06/caretaker"
description = "A meh cleanup class."
version = "1.0.1"
license = "MIT"
authors = ["Coltrane Willsey"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"